---
- name: Docker Add Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Docker Add Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
- name: Install Application
  apt: 
    name: [
      'vim',
      'git',
      'docker-ce', 'docker-ce-cli', 'containerd.io', 
      'python3-pip',
      'ufw'
    ]
    update_cache: yes
- name: Install Python Docker
  pip:
    name:
      - docker
      - docker-compose